inherit_gem:
  rubocop-shopify: rubocop.yml
  
require:
  - rubocop-rspec

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - describe
    - to
    - to_not
    - require
    - require_relative
    - raise
    - print
    - source
    - ruby
